Added clipboard to libra

diff --git a/bin/libra b/bin/libra
--- a/bin/libra
+++ b/bin/libra
@@ -4,6 +4,7 @@
 #
 # Needs the following to function properly:
 #   tree
+#   xclip
 #
 # This script is not meant to be used directly
 # from the command line. Its crudely written
@@ -12,7 +13,9 @@
 # TODO:
 #   * Fix bug that breaks if $BMLIB ends with '/'
 #   * Integrate git into this.
-#   * Maybe make the code more like a program than script
+#   * Maybe make the code more like a program than script,
+#       for now, this script should do, but it could be much better.
+#   * clip shouldn't use cat, instead just get the first line.
 
 # Don't put a '/' at the end or the code will fail.
 BMLIB=$HOME/lib/bookmarks
@@ -91,7 +94,11 @@ cmd_show() {
 cmd_clip() {
     # Argument list
     #   $1 - Bookmark name and location
-    echo ""
+    if [ -f $BMLIB/$1 ]; then
+        cat $BMLIB/$1 | xclip -selection "clipboard"
+    else
+        (>&2 echo "ERROR: File does not exist (cmd_show): $1")
+    fi
 }
 
 cmd_edit() {
